package com.chatbot.chatbot.service;

import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.google.gson.JsonElement;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.Base64;

@Service
public class AIService {

    @Value("${ai.api.key}")
    private String apiKey;

    @Value("${ai.model}")
    private String model;

    @Value("${n8n.webhook.url:}")
    private String n8nWebhookUrl;

    private final HttpClient httpClient = HttpClient.newBuilder()
            .connectTimeout(Duration.ofSeconds(15))
            .build();

    private final Gson gson = new Gson();

    /**
     * Checks if the application is running in Mock Mode due to missing/default API key.
     */
    public boolean isMockMode() {
        return apiKey == null || 
               apiKey.trim().isEmpty() || 
               apiKey.equals("YOUR_API_KEY") || 
               apiKey.contains("${AI_API_KEY}");
    }

    /**
     * Sends a completions request to either Google Gemini or OpenRouter API based on key prefix.
     *
     * @param prompt     The instruction/prompt.
     * @param imageBytes Optional bytes of the uploaded image.
     * @param mimeType   Optional mime type of the image.
     * @return The response text generated by the AI.
     * @throws Exception if HTTP call fails or API returns error status.
     */
    public String generateContent(String prompt, byte[] imageBytes, String mimeType) throws Exception {
        if (n8nWebhookUrl != null && !n8nWebhookUrl.trim().isEmpty()) {
            return callN8nWebhook(prompt, imageBytes, mimeType);
        }

        if (isMockMode()) {
            throw new IllegalStateException("AI service is in mock mode. Live API key is missing.");
        }

        if (apiKey.startsWith("AIzaSy")) {
            return callGoogleGemini(prompt, imageBytes, mimeType);
        } else {
            return callOpenRouter(prompt, imageBytes, mimeType);
        }
    }

    private String callGoogleGemini(String prompt, byte[] imageBytes, String mimeType) throws Exception {
        // Construct request body using Google Gemini structure
        JsonObject requestObj = new JsonObject();
        JsonArray contents = new JsonArray();
        JsonObject contentObj = new JsonObject();
        JsonArray parts = new JsonArray();

        // 1. Text Prompt part
        JsonObject textPart = new JsonObject();
        textPart.addProperty("text", prompt);
        parts.add(textPart);

        // 2. Image Part (if available)
        if (imageBytes != null && mimeType != null) {
            JsonObject imagePart = new JsonObject();
            JsonObject inlineData = new JsonObject();
            inlineData.addProperty("mimeType", mimeType);
            inlineData.addProperty("data", Base64.getEncoder().encodeToString(imageBytes));
            imagePart.add("inlineData", inlineData);
            parts.add(imagePart);
        }

        contentObj.add("parts", parts);
        contents.add(contentObj);
        requestObj.add("contents", contents);

        String jsonPayload = gson.toJson(requestObj);
        
        // Resolve google gemini model name
        String googleModel = model;
        if (googleModel == null || googleModel.contains(":") || googleModel.contains("/")) {
            googleModel = "gemini-1.5-flash"; // default stable free vision model on Google
        }
        
        String url = "https://generativelanguage.googleapis.com/v1beta/models/" + googleModel + ":generateContent?key=" + apiKey;

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            String errorMsg = "Google Gemini API call failed with status: " + response.statusCode();
            try {
                JsonObject errorJson = JsonParser.parseString(response.body()).getAsJsonObject();
                if (errorJson.has("error")) {
                    JsonObject errorDetail = errorJson.getAsJsonObject("error");
                    errorMsg += ". Details: " + errorDetail.get("message").getAsString();
                }
            } catch (Exception ignored) {}
            throw new RuntimeException(errorMsg);
        }

        // Parse response from Google
        JsonObject responseObj = JsonParser.parseString(response.body()).getAsJsonObject();
        JsonArray candidates = responseObj.getAsJsonArray("candidates");
        if (candidates != null && candidates.size() > 0) {
            JsonObject firstCandidate = candidates.get(0).getAsJsonObject();
            JsonObject content = firstCandidate.getAsJsonObject("content");
            if (content != null) {
                JsonArray resParts = content.getAsJsonArray("parts");
                if (resParts != null && resParts.size() > 0) {
                    return resParts.get(0).getAsJsonObject().get("text").getAsString();
                }
            }
        }

        throw new RuntimeException("Unexpected empty response from Google Gemini API.");
    }

    private String callOpenRouter(String prompt, byte[] imageBytes, String mimeType) throws Exception {
        // Construct request body for OpenRouter (OpenAI-compatible format)
        JsonObject requestObj = new JsonObject();
        requestObj.addProperty("model", model);
        requestObj.addProperty("max_tokens", 1000);

        JsonArray messages = new JsonArray();
        JsonObject messageObj = new JsonObject();
        messageObj.addProperty("role", "user");

        JsonArray content = new JsonArray();

        // 1. Text Prompt part
        JsonObject textPart = new JsonObject();
        textPart.addProperty("type", "text");
        textPart.addProperty("text", prompt);
        content.add(textPart);

        // 2. Image Part (if available)
        if (imageBytes != null && mimeType != null) {
            JsonObject imagePart = new JsonObject();
            imagePart.addProperty("type", "image_url");
            
            JsonObject imageUrlObj = new JsonObject();
            String base64Image = Base64.getEncoder().encodeToString(imageBytes);
            imageUrlObj.addProperty("url", "data:" + mimeType + ";base64," + base64Image);
            
            imagePart.add("image_url", imageUrlObj);
            content.add(imagePart);
        }

        messageObj.add("content", content);
        messages.add(messageObj);
        requestObj.add("messages", messages);

        String jsonPayload = gson.toJson(requestObj);
        String url = "https://openrouter.ai/api/v1/chat/completions";

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + apiKey)
                .header("HTTP-Referer", System.getenv("FRONTEND_URL") != null ? System.getenv("FRONTEND_URL") : "https://github.com/AuraBot")
                .header("X-Title", "AuraBot")
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            String errorMsg = "OpenRouter API call failed with status: " + response.statusCode();
            try {
                JsonObject errorJson = JsonParser.parseString(response.body()).getAsJsonObject();
                if (errorJson.has("error")) {
                    JsonObject errorDetail = errorJson.getAsJsonObject("error");
                    errorMsg += ". Details: " + (errorDetail.has("message") ? errorDetail.get("message").getAsString() : errorDetail.toString());
                }
            } catch (Exception ignored) {}
            throw new RuntimeException(errorMsg);
        }

        // Parse response from OpenRouter
        JsonObject responseObj = JsonParser.parseString(response.body()).getAsJsonObject();
        JsonArray choices = responseObj.getAsJsonArray("choices");
        if (choices != null && choices.size() > 0) {
            JsonObject firstChoice = choices.get(0).getAsJsonObject();
            JsonObject message = firstChoice.getAsJsonObject("message");
            if (message != null && message.has("content")) {
                return message.get("content").getAsString();
            }
        }

        throw new RuntimeException("Unexpected empty response from OpenRouter API.");
    }

    private String callN8nWebhook(String prompt, byte[] imageBytes, String mimeType) throws Exception {
        JsonObject requestObj = new JsonObject();
        requestObj.addProperty("message", prompt);
        requestObj.addProperty("chatInput", prompt);
        requestObj.addProperty("sessionId", "springboot-session");

        if (imageBytes != null && mimeType != null) {
            String base64Image = Base64.getEncoder().encodeToString(imageBytes);
            requestObj.addProperty("base64Image", base64Image);
            requestObj.addProperty("mimeType", mimeType);
        }

        String jsonPayload = gson.toJson(requestObj);

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(n8nWebhookUrl))
                .header("Content-Type", "application/json")
                .POST(HttpRequest.BodyPublishers.ofString(jsonPayload))
                .build();

        HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200 && response.statusCode() != 201) {
            throw new RuntimeException("n8n Webhook API call failed with status: " + response.statusCode());
        }

        // Parse response from n8n
        try {
            JsonElement jsonElement = JsonParser.parseString(response.body());
            if (jsonElement.isJsonObject()) {
                JsonObject responseObj = jsonElement.getAsJsonObject();
                if (responseObj.has("output")) {
                    return responseObj.get("output").getAsString();
                } else if (responseObj.has("response")) {
                    return responseObj.get("response").getAsString();
                } else if (responseObj.has("text")) {
                    return responseObj.get("text").getAsString();
                } else if (responseObj.has("message")) {
                    return responseObj.get("message").getAsString();
                } else if (responseObj.has("reply")) {
                    return responseObj.get("reply").getAsString();
                } else if (responseObj.has("data")) {
                    JsonElement dataElement = responseObj.get("data");
                    if (dataElement.isJsonObject() && dataElement.getAsJsonObject().has("output")) {
                        return dataElement.getAsJsonObject().get("output").getAsString();
                    }
                    return dataElement.toString();
                }
            } else if (jsonElement.isJsonArray()) {
                JsonArray jsonArray = jsonElement.getAsJsonArray();
                if (jsonArray.size() > 0 && jsonArray.get(0).isJsonObject()) {
                    JsonObject firstObj = jsonArray.get(0).getAsJsonObject();
                    if (firstObj.has("output")) {
                        return firstObj.get("output").getAsString();
                    } else if (firstObj.has("response")) {
                        return firstObj.get("response").getAsString();
                    } else if (firstObj.has("text")) {
                        return firstObj.get("text").getAsString();
                    }
                }
            }
        } catch (Exception ignored) {
            // Fallback to raw response body if parsing fails
        }

        return response.body();
    }
}
